sudo: false
language: java
dist: trusty
cache:
  directories:
    - $HOME/.m2

jdk:
  - oraclejdk8
  
script: "mvn cobertura:cobertura"

after_success:
  - bash <(curl -s https://codecov.io/bash)