codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "50...100"

  status:
    project: yes
    patch: yes
    changes: no

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach, diff, flags, files, footer"
  behavior: default
  require_changes: no
  
ignore:
#generated
  - "src/main/java/xdean/reflect/getter/internal/util/ActionE0.java"
  - "src/main/java/xdean/reflect/getter/internal/util/ExceptionUtil.java"
  - "src/main/java/xdean/reflect/getter/internal/util/FuncE0.java"
  - "src/main/java/xdean/reflect/getter/internal/util/PrimitiveTypeUtil.java"
  - "src/main/java/xdean/reflect/getter/internal/util/ReflectUtil.java"
  - "src/main/java/xdean/reflect/getter/internal/util/TaskUtil.java"
  - "src/main/java/xdean/reflect/getter/internal/util/UnsafeUtil.java"
  - "src/main/java/xdean/reflect/getter/ReflectWithoutString.java"
#end
